services:
  auth-service:
    build:
      context: ./services/auth-service
      dockerfile: Dockerfile
    container_name: smartstay-auth-service
    environment:
      APP_ENV: dev
      PORT: 8081
      CONFIG_PATH: configs/config.dev.yaml
      DB_HOST: host.docker.internal
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: admin
      DB_NAME: auth_service
      DB_SSL_MODE: disable
      JWT_SECRET: local-dev-secret
    ports:
      - "8081:8081"
